### ISSUE TITLE
Dates in future 

### ISSUE THREAD

**Issue by timriffe** [SapereAude859/Covid19TH-DailyData#2]
Thanks a ton for collating this data! 
I'm noticing a date anomaly in this file:
[dataset/csv/cases.csv](https://raw.githubusercontent.com/pluz85/Covid19TH-DailyData/master/dataset/csv/cases.csv)

Here a snapshot of the first few date entries of `ConfirmDate`, as rendered in the browser:
![image](https://user-images.githubusercontent.com/904603/105042180-36f22380-5a64-11eb-8850-9b75e9c72ebb.png)

Thanks for having a look, I'm not sure if this is also an issue elsewhere

**Comment by timriffe** [comment]
seems to have gone away now, so closing the issue

**Comment by SapereAude859** [comment]
I'm really sorry for late check on it. Seems the api endpoint has their own error. Thx U so much for notice 😀
